### ISSUE TITLE
Punctuate and correct spellings in IntroActivity.java comments

### ISSUE THREAD

**Issue by nadchif** [nadchif/headset-control-plus#12]
**Good for first timers**

CURRENT ISSUE: Not all the comments within [IntroActivity.java](https://github.com/nadchif/headset-control-plus/blob/master/app/src/main/java/com/chif/headsetcontrolplus/IntroActivity.java) are properly punctuated. For example, if you go to line 19, you find
```
    // add welcome slide
```
WHAT WE NEED: The punctuation and capitalization should be fixed. For example, line 19 would become:
```
    // Add welcome slide.
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/headset-control-plus/blob/master/CONTRIBUTING.md)

**Comment by AMFIRNAS** [comment]
I am on it
