### ISSUE TITLE
Punctuate and correct spellings in IntroSlideSetup.java comments

### ISSUE THREAD

**Issue by nadchif** [nadchif/headset-control-plus#13]
**Good for first timers**

CURRENT ISSUE: Not all the comments within [IntroActivity.java](https://github.com/nadchif/headset-control-plus/blob/master/app/src/main/java/com/chif/headsetcontrolplus/IntroSlideSetup.java) are properly punctuated. For example, if you go to line 19, you find
```
    //check if signal is received. if false is returned, user cannot advance to next slide
```
WHAT WE NEED: The punctuation and capitalization should be fixed. For example, line 19 would become:
```
    // Check if signal is received. If false is returned, user cannot advance to next slide
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/headset-control-plus/blob/master/CONTRIBUTING.md)

**Comment by AMFIRNAS** [comment]
I am on it
