### ISSUE TITLE
Implement Take photo

### ISSUE THREAD

**Issue by nadchif** [nadchif/headset-control-plus#17]
This issue may not be ideal for first timers. If you want first timer friendly issues, kindly go [here](https://github.com/nadchif/headset-control-plus/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only)

**CURRENT STATUS**
Headset Control Plus works well, as expected. The actions currently supported are:
* Increase Volume
* Decrease Volume
* Mute
* Play/Pause
* Next Track
* Previous Track
* Toggle Flashlight
* Strava (Start/Stop Recording)
* Use System Default

**WHAT IS NEEDED**
Implement **Take photo** as one of the actions

**ADDITIONAL CONTEXT**
If you have suggestions or think of a better idea regarding this issue, we are open to discussion.

For a step by step guide on how to contribute. See [CONTRIBUTING.md](https://github.com/nadchif/headset-control-plus/blob/master/CONTRIBUTING.md)

**Comment by krpouncy** [comment]
Hi, could I take a shot at this?

**Comment by nadchif** [comment]
> Hi, could I take a shot at this?

Yes, please. Thank you ☺

**Comment by krpouncy** [comment]
When the action is triggered, should the camera app open and take a snapshot or should the app take a photo in the background and save to directory?

**Comment by nadchif** [comment]
> When the action is triggered, should the camera app open and take a snapshot or should the app take a photo in the background and save to directory?

Either one is fine. Do you have a preference?

**Comment by krpouncy** [comment]
Maybe there can be an option for both 🤔? Open the camera or Take a Picture (and save to gallery)

**Comment by nadchif** [comment]
Sounds good 👍 I like it ☺

**Comment by nadchif** [comment]
@krpouncy thanks to you, these features are now available in the Beta version on Playstore
