### ISSUE TITLE
Punctuate and correct spellings in FlashlightProvider.java comments

### ISSUE THREAD

**Issue by nadchif** [nadchif/headset-control-plus#6]
**Good for first timers**

CURRENT ISSUE: Not all the comments within [FlashlightProvider.java](https://github.com/nadchif/headset-control-plus/blob/master/app/src/main/java/com/chif/headsetcontrolplus/providers/FlashlightProvider.java) are properly punctuated. For example, if you go to line 28, you find
```
   * handles interactions between Camera/Flashlight and the app

```
WHAT WE NEED: The punctuation and capitalization should be fixed. For example, line 28 would become:
```
   * Handles interactions between Camera/Flashlight and the app.
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/headset-control-plus/blob/master/CONTRIBUTING.md)

**Comment by Satzyakiz** [comment]
Hello, I would like to do the changes. Please assign me. This would be my first issue !

**Comment by nadchif** [comment]
@Satzyakiz thank you. Please proceed
